Add DocBoy emulator. Run ax6 roms on DMG too.
gbdev/GBEmulatorShootout pull request #26
Opened 2024-04-16 20:58 UTC by Docheinstein

Changes introduced by this PR:
* Adds DocBoy emulator to the suite (#24).
* Remove the CGB requirement of the ax6 test roms: now they run on DMG too (#25).
 
As a consequence, this PR also update usages of Windows commands and Python packages that are not supported yet by the GitHub actions.

Commits:
* b5f23e51887d9de5a47daa63d7c444e8cb7c0b79: Add DocBoy emulator.
* 868c6ea251f1fb8874cb7a50b3635cb55ead0a66: Replace Extract-7Zip with Expand-7ZipArchive.
* 50436eda6cebe30ceff69912037d10d43dc8dcc7: Replace distutils.dir_util.copy_tree with shutil.copytree.
* 7c3fc900c345c3e30ce5c133f9811d0601dc67e0: Run ax6 roms on DMG.

Closes #24.
Closes #25.

2024-05-18 12:40 UTC, Docheinstein commented
I guess the workflow failed because I don't have the permissions/I am not a contributor??

![Screenshot from 2024-05-18 14-33-50](https://github.com/daid/GBEmulatorShootout/assets/23169541/738ca9db-0127-43aa-8379-8465c856c24c)

By the way, please tell me if there's something of this PR I could improve or change.

2026-03-20 18:13 UTC, vulcandth commented
I'm going to work on this in a bit once I get the other emulators updated.

2026-03-20 18:13 UTC, avivace requested changes
The changes related to DocBoy seem ok to me but:

- ax6 test roms results are updated (?)
- there are some unrelated changes in the ares emulator and in the main pipeline

2026-03-20 18:13 UTC, avivace commented on .github/workflows/main.yml
> +          Expand-7ZipArchive -Path C:\Scream3.6.zip -DestinationPath C:\Scream
unrelated change?

2026-03-20 18:13 UTC, avivace commented on emulators/ares.py
> +from shutil import copytree
unrelated change?

2026-03-20 18:13 UTC, avivace commented on emulators/ares.py
> +          copytree(os.path.join("emu/ares", os.listdir("emu/ares")[0]), "emu/ares")
unrelated change?

2026-03-21 10:19 UTC, Docheinstein commented
Hi everyone.

I've just noticed that the original repo has been moved and has been updated recently, great.

I've noticed that there a few conflicts now: I'll update my branch so that we can make the merge smoother.

Furthermore, now DocBoy also CGB in addition to DMG, so I'll consider add it as well.

2026-03-21 10:21 UTC, Docheinstein commented on emulators/ares.py
> +from shutil import copytree
At the time of my PR this was making the pipeline fail, as distutils has been removed starting from Python 3.12 [release note](https://docs.python.org/3/whatsnew/3.12.html).

I'll revert this and the other changes, as they have already been fixed in the main branch.

2026-03-21 12:21 UTC, vulcandth requested changes

2026-03-21 12:21 UTC, vulcandth commented on testroms/ax6.py
> +    Test("ax6/rtc3test-3.gb", runtime=20.0),
Please revert the ax6 test changes for now. This will be changed, but not in this PR. Thanks!

2026-03-21 13:37 UTC, Docheinstein commented on testroms/ax6.py
> +    Test("ax6/rtc3test-3.gb", runtime=20.0),
Sure. Done!

2026-03-21 13:41 UTC, vulcandth requested changes
This looks good, but we need to add the emulator into the CI as well. I can take care of this and push an update to this PR myself.

Furthermore, I have  change I am making to fix #65 and #66 and I'd like to wait to merge this until after that PR is created/merged.

2026-03-21 18:33 UTC, avivace commented
> This looks good, but we need to add the emulator into the CI as well. I can take care of this and push an update to this PR myself.
> 
> Furthermore, I have change I am making to fix #65 and #66 and I'd like to wait to merge this until after that PR is created/merged.

Can we merge without the CI part at the moment? That shouldn't need any other fix, right? Then we can work on the CI part after those other things you mentioned are fixed.

2026-03-21 18:45 UTC, vulcandth commented
This needs a CI workflow like the other emulators.

See the GitHub CI workflow files

2026-03-21 18:49 UTC, Docheinstein commented
> This needs a CI workflow like the other emulators.
> 
> See the GitHub CI workflow files

All right, didn't know about the CI files, I'll add it later then.

2026-03-21 18:51 UTC, avivace commented
> This needs a CI workflow like the other emulators.
> 
> See the GitHub CI workflow files

I know, but merging what we have won't hurt (we simply won't have the results just yet in the gh-pages branch) and CI can be added later - I just don't want to have this blocked nor blocking if there's not a real reason for it.

2026-03-21 19:08 UTC, vulcandth commented
> > This needs a CI workflow like the other emulators.
> > 
> > See the GitHub CI workflow files
> 
> I know, but merging what we have won't hurt (we simply won't have the results just yet in the gh-pages branch) and CI can be added later - I just don't want to have this blocked nor blocking if there's not a real reason for it.

The main blocker was that other PR that just got merged because I expected a merge conflict.

My full intent was to fix the merge conflict here and add the CI myself then merge this PR after. Next on my to-do list. But I'm about to see a movie with the wife now so it would be after.

If you would like to fix the merge conflict and merge without the CI that is fine. I'll add the CI later. No worries. 😊

2026-03-21 19:32 UTC, Rangi42 commented
Although also, it's not really "blocking" anything to leave this open, since whether or not it gets merged as-is, Vulcandth's next intended task is to add CI for it. Unless somebody else's intended tasks need this merged first too, and they don't need CI to work for it.

2026-03-21 23:08 UTC, Docheinstein commented
In the latest commits I've solved the conflicts with upstream, added the ci-docboy.yml to the workflows and added support for DocBoy in CGB as well. Let me know if that's fine.

2026-03-22 10:26 UTC, avivace approved these changes

2026-03-22 10:31 UTC, merged